# This action updates the component version in our helm chart
# For more information see https://github.com/rabbitmq-pro/tanzu-rabbitmq-operator-chart
name: update_helm_chart

on:
  release:
    types: [published]
    
  workflow_dispatch:
    
jobs:
    create-chart-pr:
        name: Create pull request to char repo
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Checkout helm repo
          uses: actions/checkout@v4
          with:
            repository: rabbitmq-pro/tanzu-rabbitmq-operator-chart
            ref: adding_sync_operators_action_scripts
            token: ${{ secrets.GIT_HUB_INFRA_REPO_ACCESS_TOKEN }}
            path: ./tanzu-rabbitmq-operator-chart


        - name: Set tag image for tagged version
          if: startsWith(github.ref, 'refs/tags/v')
          run: | 
              BUNDLE_VERSION=${GITHUB_REF#refs/*/} 
              echo "BUNDLE_VERSION=${BUNDLE_VERSION:1}" >> $GITHUB_ENV
    
        # For manual testing
        - name: Set tag image for test version
          if: startsWith(github.ref, 'refs/tags/v') == false
          run: | 
            echo "BUNDLE_VERSION=1.0.3" >> $GITHUB_ENV

        - name: Update helm released version
          env:
            GH_TOKEN: ${{ secrets.GIT_HUB_INFRA_REPO_ACCESS_TOKEN }}
            BUNDLE_VERSION: ${{ env.BUNDLE_VERSION }}
          run: | 
            cd ./tanzu-rabbitmq-operator-chart
            git config --global user.name "rabbitmq-ci"
            git config --global user.email rabbitmq-ci@vmware.com
            git branch rabbitmq_default_user_credential_$BUNDLE_VERSION
            git checkout rabbitmq_default_user_credential_$BUNDLE_VERSION
            sed -i -e "s/cluster-operator:.*/cluster-operator:$BUNDLE_VERSION/" ./Chart.yaml
            python3 ./scripts/update_cluster_operator_value_version.py ./values.yaml "rabbitmqoperator/default-user-credential-updater" $BUNDLE_VERSION
            git add .
            git commit -m "Updating RabbitMQ default user credential versions"
            git push --force origin rabbitmq_default_user_credential_$BUNDLE_VERSION
#gh pr create --title "RabbitMQ default user credential updater: Update image versions" --body "RabbitMQ default user credential updater: Update image versions" --base main



